apiVersion: apps/v1
kind: Deployment
metadata:
  name: io-deployment
  labels:
    app: io
spec:
  replicas: 2
  selector:
    matchLabels:
      app: io
  template:
    metadata:
      labels:
        app: io
    spec:
      containers:
      - name: io
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
