version: "3"
services:
    mywebapp:
        build: .
        image: io-deployment-f9b5dfd95-pw4v5
        container_name: containerorigin
        ports:
            - 86:80
        networks:
          - network

networks:
  network: {}